version: "3"
services:
  app:    
    image: converter:latest 
    build:
      #context: ./ # pointing to directory with dockerfile
      context: ./      
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./config.php:/var/www/html/HRProprietary/HRConvert2/config.php
# uncomment the below line to expose temporary upload folder as a volume
#     - ./files:/home/converter:rw
